/* songs.js — the built-in track list and how their audio is obtained.
 *
 * Two delivery paths, because browsers block fetch()/XHR on file:// origins:
 *   - opened by double-clicking index.html  -> base64 from songs/tracks.js
 *   - served over http (local server, Pages) -> fetch songs/<file>.mp3
 * tracks.js is generated by tools/embed-songs.py and is optional; without it the
 * built-in tracks simply need http.
 */
(function () {
  'use strict';

  // note = decoded length, floored the same way the in-game status line formats it
  // (80.8s reads as 1:20, not 1:21) so the two never disagree. Do not take these
  // from the mp3 header: the files are VBR and a bitrate guess reads far too long.
  var builtin = [
    { id: 'koi-no-beat',         title: '恋のビート',     note: '1:20', file: 'songs/koi-no-beat.mp3' },
    { id: 'niji-wo-koete',       title: '虹を越えて',     note: '1:21', file: 'songs/niji-wo-koete.mp3' },
    { id: 'koi-no-melody',       title: '恋のメロディ',   note: '1:22', file: 'songs/koi-no-melody.mp3' },
    { id: 'pocket-no-oku-de',    title: 'ポケットの奥で', note: '1:42', file: 'songs/pocket-no-oku-de.mp3' }
  ];

  function base64ToArrayBuffer(b64) {
    var bin = atob(b64);
    var len = bin.length;
    var bytes = new Uint8Array(len);
    for (var i = 0; i < len; i++) bytes[i] = bin.charCodeAt(i);
    return bytes.buffer;
  }

  function bytesFor(track) {
    if (RG.embedded && RG.embedded[track.id]) {
      // Decoding ~2MB of base64 blocks briefly; let the caller paint a status first.
      return Promise.resolve(base64ToArrayBuffer(RG.embedded[track.id]));
    }
    return fetch(track.file).then(function (res) {
      if (!res.ok) throw new Error('HTTP ' + res.status);
      return res.arrayBuffer();
    }).catch(function (err) {
      throw new Error(
        '수록곡을 읽지 못했습니다 (' + err.message + '). ' +
        'songs/tracks.js 를 생성하거나(python tools/embed-songs.py) ' +
        '로컬 서버로 열어 주세요.'
      );
    });
  }

  // Resolves to a decoded AudioBuffer ready for analysis.
  function load(track) {
    return bytesFor(track).then(function (ab) {
      return RG.audio.ctx().decodeAudioData(ab);
    });
  }

  RG.songs = { builtin: builtin, load: load };
})();
