/* render.js — the corridor, and everything drawn inside it.
 *
 * v1 was a flat 2D lane chart. Here the playfield is a box in 3D that the notes
 * fly down: they are born at the far end, grow as they approach, and are played
 * when they reach the near end — the hit plane, which is where the grid of eight
 * touch targets is painted.
 *
 * The projection is derived from the viewport at resize, not hard-coded, so the
 * hit plane always lands in the same place on screen whatever the aspect ratio:
 *
 *   unit  — screen pixels per world unit AT THE HIT PLANE (also one cell wide)
 *   focal — unit * zNear, so that focal/zNear == unit falls out
 *   camH  — camera height above the grid centre, in world units
 *
 * Reads gameplay state and never writes to it, apart from expiring its own
 * finished visual effects.
 */
(function () {
  'use strict';

  var C = RG.config, V = RG.config.VIEW;
  var cv = RG.el.cv, ctx = RG.el.ctx;

  var W = 0, H = 0, dpr = 1;
  var unit = 60, focal = 60, horizonY = 60, hitCY = 400, camH = 5, rowSpread = 1;

  // The two characters from the menu, so a run is cheered on by the same pair that
  // introduces the game rather than by a bare number. The panda is artwork on
  // disk; the cat is generated by ../js/icon.js and arrives as an SVG data URI.
  // Both draw only once loaded — until then the banner is the number alone.
  var mascots = { panda: null, cat: null };
  (function () {
    var p = new Image();
    p.onload = function () { mascots.panda = p; };
    p.src = '../panda-heart.png';
    var c = new Image();
    c.onload = function () { mascots.cat = c; };
    c.src = RG.icon.dataUri();
  })();

  function resize() {
    var wrap = cv.parentElement;
    dpr = Math.min(window.devicePixelRatio || 1, 2);
    W = wrap.clientWidth; H = wrap.clientHeight;
    cv.width = Math.round(W * dpr); cv.height = Math.round(H * dpr);
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);

    // Four cells across is what sets the width; the height term only keeps a
    // short landscape stage from pushing the row off the bottom.
    unit = Math.max(28, Math.min(W * 0.20, H * 0.22));
    focal = unit * V.zNear;
    // A cell is one world unit wide, but not necessarily one tall. On a tall
    // phone the width is what limits the cell size, and a square cell then
    // leaves most of the stage empty and the target smaller than a thumb
    // deserves — so the cell is stretched until the row is about a fifth of the
    // stage. Capped: past 1.5 the cells stop reading as cells and start reading
    // as lanes, which is the v1 game.
    rowSpread = Math.max(1, Math.min(1.5, (H * 0.20) / unit));
    // The corridor gets the top of the stage and the grid sits low, where a thumb
    // already rests — a row this shallow floated uncomfortably high in the middle.
    // Below it a band stays clear for the judgement label, the one place on screen
    // a note never flies through.
    horizonY = H * 0.10;
    hitCY = H * 0.71;
    camH = (hitCY - horizonY) / unit;
  }

  // World (x right, y down, z away) to screen. s is the scale at that depth —
  // multiply any world length by it to get pixels.
  function proj(wx, wy, z) {
    var s = focal / z;
    return { x: W / 2 + wx * s, y: horizonY + (camH + wy) * s, s: s };
  }

  // Progress 0 (just spawned, far) to 1 (at the hit plane) for a note dt seconds
  // away, and the depth that maps to.
  function depthFor(dt, approach) {
    var p = 1 - dt / approach;
    return V.zFar + (V.zNear - V.zFar) * p;
  }

  function colX(col) { return (col - (C.COLS - 1) / 2); }   // -1.5 .. 1.5
  // Centred on the corridor's axis: with one row that is the middle of the
  // screen, and the formula still spreads evenly if a row is ever added back.
  function rowY(row) { return (row - (C.ROWS - 1) / 2) * rowSpread; }
  function halfH() { return (C.ROWS / 2) * rowSpread; }

  // Where a cell's touch target sits on screen. game.js judges against this and
  // nothing else: the flight is animation, the target never moves.
  function cellCenter(col, row) {
    return proj(colX(col), rowY(row), V.zNear);
  }
  function cellUnit() { return unit; }

  function clear() { ctx.clearRect(0, 0, W, H); }

  function roundRect(x, y, w, h, r) {
    r = Math.min(r, w / 2, h / 2);
    ctx.beginPath();
    ctx.moveTo(x + r, y);
    ctx.arcTo(x + w, y, x + w, y + h, r);
    ctx.arcTo(x + w, y + h, x, y + h, r);
    ctx.arcTo(x, y + h, x, y, r);
    ctx.arcTo(x, y, x + w, y, r);
    ctx.closePath();
  }

  // The mascot's heart, as a path. r is the half-width.
  function heartPath(cx, cy, r) {
    ctx.beginPath();
    ctx.moveTo(cx, cy + r * 0.92);
    ctx.bezierCurveTo(cx - r * 1.45, cy + r * 0.05, cx - r * 0.82, cy - r * 1.12, cx, cy - r * 0.32);
    ctx.bezierCurveTo(cx + r * 0.82, cy - r * 1.12, cx + r * 1.45, cy + r * 0.05, cx, cy + r * 0.92);
    ctx.closePath();
  }

  function fillArrow(cx, cy, r, dir, color) {
    ctx.save();
    ctx.translate(cx, cy);
    ctx.rotate(C.DIRS[dir].ang);      // the path below points up before rotation
    ctx.beginPath();
    ctx.moveTo(0, -r * 0.70);
    ctx.lineTo(r * 0.58, r * 0.02);
    ctx.lineTo(r * 0.24, r * 0.02);
    ctx.lineTo(r * 0.24, r * 0.68);
    ctx.lineTo(-r * 0.24, r * 0.68);
    ctx.lineTo(-r * 0.24, r * 0.02);
    ctx.lineTo(-r * 0.58, r * 0.02);
    ctx.closePath();
    ctx.fillStyle = color;
    ctx.fill();
    ctx.restore();
  }

  // ---------- the corridor ----------
  // A rectangle in world space, drawn at one depth. Used for the hit frame, the
  // far mouth, and the rings that stream toward the player.
  function boxAt(z, alpha, width, color) {
    var hx = V.gridHalf, hy = halfH();
    var tl = proj(-hx, -hy, z), br = proj(hx, hy, z);
    ctx.globalAlpha = alpha;
    ctx.strokeStyle = color;
    ctx.lineWidth = width;
    ctx.strokeRect(tl.x, tl.y, br.x - tl.x, br.y - tl.y);
    ctx.globalAlpha = 1;
  }

  function line3(x1, y1, z1, x2, y2, z2, alpha, width, color) {
    var a = proj(x1, y1, z1), b = proj(x2, y2, z2);
    ctx.globalAlpha = alpha;
    ctx.strokeStyle = color;
    ctx.lineWidth = width;
    ctx.beginPath();
    ctx.moveTo(a.x, a.y);
    ctx.lineTo(b.x, b.y);
    ctx.stroke();
    ctx.globalAlpha = 1;
  }

  function drawCorridor(t) {
    var hx = V.gridHalf, hy = halfH();

    // Light at the far end. Depth reads almost entirely from this: without a
    // bright vanishing point the converging lines look like a flat trapezoid.
    // Kept tight — spread across the whole top it stops being a light source and
    // just washes the notes out while they are still small.
    var vp = proj(0, 0, V.zFar);
    var glow = ctx.createRadialGradient(vp.x, vp.y, 0, vp.x, vp.y, Math.max(W, H) * 0.26);
    glow.addColorStop(0, 'rgba(255,255,255,0.92)');
    glow.addColorStop(0.4, 'rgba(255,240,249,0.4)');
    glow.addColorStop(1, 'rgba(255,209,232,0)');
    ctx.fillStyle = glow;
    ctx.fillRect(0, 0, W, H);

    // Rings streaming toward the player. They carry the sense of speed that the
    // notes alone cannot: between two sparse notes the corridor would sit still.
    var RINGS = 7;
    for (var i = 0; i < RINGS; i++) {
      var p = ((t * 0.42) + i / RINGS) % 1;
      if (p < 0) p += 1;
      var z = V.zFar + (V.zNear - V.zFar) * p;
      boxAt(z, 0.10 + p * 0.16, 1 + p * 1.4, '#ff2e88');
    }

    // Edges of the box, plus the column and row dividers running its length.
    for (var c = 0; c <= C.COLS; c++) {
      var x = -hx + c;
      var edge = (c === 0 || c === C.COLS);
      line3(x, -hy, V.zFar, x, -hy, V.zNear, edge ? 0.5 : 0.22, edge ? 2 : 1, '#ff2e88');
      line3(x,  hy, V.zFar, x,  hy, V.zNear, edge ? 0.5 : 0.22, edge ? 2 : 1, '#ff2e88');
    }
    line3(-hx, -hy, V.zFar, -hx, -hy, V.zNear, 0.45, 2, '#b57bee');
    line3( hx, -hy, V.zFar,  hx, -hy, V.zNear, 0.45, 2, '#b57bee');

    boxAt(V.zFar, 0.5, 1.5, '#ff9cc9');
  }

  // The near wall: an opaque panel, the combo faint behind the glass, then the
  // eight targets on top.
  //
  // The panel is not decoration. Every line of the corridor converges on the hit
  // frame, and the floor lines in particular run all the way down across the
  // target area — seen through translucent cells they read as cracks. Stopping
  // the corridor at an opaque wall is what makes the targets legible.
  function drawStage(now, fx) {
    var hx = V.gridHalf, hy = halfH();
    var tl = proj(-hx, -hy, V.zNear), br = proj(hx, hy, V.zNear);
    var pw = br.x - tl.x, ph = br.y - tl.y;

    ctx.fillStyle = 'rgba(255,240,248,0.94)';
    roundRect(tl.x - 5, tl.y - 5, pw + 10, ph + 10, unit * 0.12);
    ctx.fill();

    var pad = unit * 0.06;
    var cw = unit - pad * 2, ch = unit * rowSpread - pad * 2;
    for (var col = 0; col < C.COLS; col++) {
      for (var row = 0; row < C.ROWS; row++) {
        var c = cellCenter(col, row);
        var x = c.x - cw / 2, y = c.y - ch / 2;
        var flash = now - ((fx.cellFlash[col] && fx.cellFlash[col][row]) || -9e9);
        var lit = flash < 150;

        ctx.fillStyle = lit ? C.COL_COLORS[col] : 'rgba(255,255,255,0.8)';
        ctx.globalAlpha = lit ? (1 - flash / 150) * 0.55 + 0.25 : 1;
        roundRect(x, y, cw, ch, Math.min(cw, ch) * 0.24);
        ctx.fill();
        ctx.globalAlpha = 1;

        ctx.strokeStyle = C.COL_COLORS[col];
        ctx.globalAlpha = lit ? 1 : 0.6;
        ctx.lineWidth = lit ? 4 : 2.5;
        ctx.stroke();
        ctx.globalAlpha = 1;
      }
    }

    // The hit plane itself, so it is obvious where "now" is in the corridor.
    boxAt(V.zNear, 0.9, 4, 'rgba(255,255,255,0.95)');
    boxAt(V.zNear, 0.85, 2, '#ff2e88');
  }

  // ---------- notes ----------
  // A tail is a ribbon receding into the corridor: sampled at a handful of depths
  // and stroked, rather than drawn as one quad, because perspective makes it
  // narrow toward the far end and a straight line would not.
  function drawTail(note, t, approach, active) {
    var wx = colX(note.col), wy = rowY(note.row);
    var headDt = active ? 0 : Math.max(0, note.time - t);
    var tailDt = Math.max(headDt, note.holdEnd - t);
    if (tailDt <= headDt + 0.001) return;

    var STEPS = 10;
    var left = [], right = [];
    for (var i = 0; i <= STEPS; i++) {
      var dt = headDt + (tailDt - headDt) * (i / STEPS);
      if (dt > approach) break;
      var z = depthFor(dt, approach);
      var p = proj(wx, wy, z);
      var hw = 0.19 * p.s;
      left.push([p.x - hw, p.y]);
      right.push([p.x + hw, p.y]);
    }
    if (left.length < 2) return;

    ctx.beginPath();
    ctx.moveTo(left[0][0], left[0][1]);
    for (var a = 1; a < left.length; a++) ctx.lineTo(left[a][0], left[a][1]);
    for (var b = right.length - 1; b >= 0; b--) ctx.lineTo(right[b][0], right[b][1]);
    ctx.closePath();

    ctx.globalAlpha = active ? 0.95 : 0.6;
    ctx.fillStyle = C.COL_COLORS[note.col];
    ctx.fill();
    ctx.globalAlpha = 1;
    ctx.strokeStyle = active ? 'rgba(255,255,255,0.95)' : 'rgba(255,255,255,0.75)';
    ctx.lineWidth = 2;
    ctx.stroke();
  }

  function drawNote(note, p, r, alpha) {
    var color = C.COL_COLORS[note.col];
    ctx.globalAlpha = alpha;

    if (note.type === C.BOMB) {
      // Deliberately not candy: a bomb has to read as "not for you" at a glance,
      // from the far end of the corridor, at a fifth of its final size.
      ctx.fillStyle = '#3b1230';
      ctx.beginPath();
      ctx.arc(p.x, p.y, r * 0.86, 0, Math.PI * 2);
      ctx.fill();
      ctx.strokeStyle = '#ff2e88';
      ctx.lineWidth = Math.max(1.5, r * 0.13);
      ctx.stroke();
      ctx.strokeStyle = 'rgba(255,255,255,0.92)';
      ctx.lineWidth = Math.max(1.5, r * 0.17);
      ctx.beginPath();
      ctx.moveTo(p.x - r * 0.34, p.y - r * 0.34); ctx.lineTo(p.x + r * 0.34, p.y + r * 0.34);
      ctx.moveTo(p.x + r * 0.34, p.y - r * 0.34); ctx.lineTo(p.x - r * 0.34, p.y + r * 0.34);
      ctx.stroke();
      ctx.globalAlpha = 1;
      return;
    }

    // Every playable note is a heart. With no second shape to be told apart from,
    // the arrow on its face is the only thing the eye has to resolve — which is
    // the whole point of dropping the tap.
    ctx.shadowColor = color;
    ctx.shadowBlur = Math.min(18, r * 0.7);
    ctx.fillStyle = color;
    heartPath(p.x, p.y, r * 0.98);
    ctx.fill();
    ctx.shadowBlur = 0;
    ctx.strokeStyle = 'rgba(255,255,255,0.92)';
    ctx.lineWidth = Math.max(1.2, r * 0.13);
    ctx.stroke();

    if (note.type === C.SLASH) {
      // Sat a little high: a heart carries its mass above its point, so an arrow
      // on the geometric centre reads as sliding off the bottom of it.
      fillArrow(p.x, p.y - r * 0.12, r * 0.74, note.dir, 'rgba(255,255,255,0.97)');
      ctx.globalAlpha = 1;
      return;
    }

    // A hold wears a ring where a slash wears an arrow: it is the one note
    // answered by staying still, so the absence of an arrow is the instruction.
    if (note.type === C.HOLD) {
      ctx.strokeStyle = 'rgba(255,255,255,0.85)';
      ctx.lineWidth = Math.max(1, r * 0.1);
      ctx.beginPath();
      ctx.arc(p.x, p.y, r * 1.3, 0, Math.PI * 2);
      ctx.stroke();
    }
    ctx.globalAlpha = 1;
  }

  // ---------- combo ----------
  // Above the mouth of the corridor: the one band of the screen a note never
  // reaches, so the number can be as large as it likes without ever covering
  // something the player has to read.
  function bandBottom() { return proj(0, -halfH(), V.zFar).y; }

  // A short bounce on every hit. Squared so it snaps and then settles, rather
  // than easing in and out like something being animated at you.
  function pop(t0, now, delay) {
    var age = now - t0 - delay;
    if (age < 0 || age > 220) return 0;
    var k = 1 - age / 220;
    return k * k * 0.30;
  }

  // How big to draw a mascot, given a nominal side. Matched by AREA rather than
  // by height: the panda is a nearly square 480x440 drawing and the cat a wide,
  // short 245x150 one, so giving them the same height — which is what the menu
  // does, and what this did at first — leaves the cat spanning half again as
  // wide and plainly reading as the bigger of the two. Equal area splits the
  // difference between them instead of loading all of it onto the cat's width.
  function mascotBox(img, side) {
    if (!img || !img.naturalWidth) return null;
    var w = img.naturalWidth, h = img.naturalHeight;
    var s = side / Math.sqrt(w * h);
    return { w: w * s, h: h * s };
  }

  function drawMascot(img, cx, cy, side, scale) {
    var b = mascotBox(img, side);
    if (!b) return;
    // Both characters are pixel art, and the menu shows them with
    // image-rendering: pixelated. Smoothed up on the canvas they turn to mush.
    var smooth = ctx.imageSmoothingEnabled;
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(img, cx - b.w * scale / 2, cy - b.h * scale / 2,
                  b.w * scale, b.h * scale);
    ctx.imageSmoothingEnabled = smooth;
  }

  function mascotWidth(img, side) {
    var b = mascotBox(img, side);
    return b ? b.w : 0;
  }

  // Every tenth combo the pair throws hearts. Positions come from the age rather
  // than from a particle list — there is nothing to keep between frames.
  // A fan of hearts from the mascot's chest. How far they reach is whatever
  // headroom the stage has left above the banner: thrown a fixed distance they
  // either leave the top of the screen mid-fade, or — once shortened enough not
  // to — never clear the mascot they came from.
  function comboHearts(x, y, age, size, headroom) {
    var p = age / 700;
    if (p < 0 || p >= 1) return;
    var reach = Math.min(size * 1.25, Math.max(0, headroom));
    ctx.globalAlpha = (1 - p) * 0.95;
    for (var i = 0; i < 5; i++) {
      var a = -Math.PI / 2 + (i - 2) * 0.5;
      var r = size * 0.26 + p * reach;
      ctx.fillStyle = i % 2 ? '#ff2e88' : '#b57bee';
      heartPath(x + Math.cos(a) * r, y + size * 0.16 + Math.sin(a) * r,
                size * 0.18 * (1 - p * 0.45));
      ctx.fill();
    }
    ctx.globalAlpha = 1;
  }

  // How far the banner reaches above and below its centre line, per the given
  // text size. Both halves are measured at full bounce, because that is when it
  // is largest and therefore when it would spill.
  var MAX_POP = 1.30;
  function bannerExtent(fs, grow) {
    var side = fs * 1.45 * grow;
    var bp = mascotBox(mascots.panda, side), bc = mascotBox(mascots.cat, side);
    var tallest = Math.max(bp ? bp.h : side, bc ? bc.h : side) / 2 * MAX_POP;
    return {
      up: tallest + side * 0.55 * 0.30,        // half height, plus the hop
      down: Math.max(tallest, fs * 0.88)       // or the COMBO label under the number
    };
  }

  function drawCombo(game, fx, now) {
    if (game.combo < 2) return;
    var bottom = bandBottom();
    var grow0 = 1 + Math.min(game.combo, 100) / 100 * 0.22;
    var fs = Math.max(14, Math.min(bottom * 0.42, 56));

    // Fit the banner to the band's height as well as the stage's width. Sized on
    // the text alone it clears the corridor on a tall phone and pokes out of the
    // top of the screen on a short landscape one, where the band is barely taller
    // than the mascots themselves.
    var ext = bannerExtent(fs, grow0);
    var avail = bottom - 6;
    if (ext.up + ext.down > avail && ext.up + ext.down > 0) {
      fs *= avail / (ext.up + ext.down);
      ext = bannerExtent(fs, grow0);
    }
    var cy = 3 + ext.up + Math.max(0, (avail - ext.up - ext.down) / 2);

    // The pair grows a little as the run does, so a long combo reads as size
    // before the number itself is read.
    var grow = grow0;
    var at = fx.comboPop || -9e9;
    var boost = pop(at, now, 0);
    // ONE scale for both. Giving the cat a delayed bounce made the pair feel
    // alive, but it also meant the two were never the same size at the same
    // instant — and while a combo is running the bounce retriggers constantly,
    // so "never" is the whole time. It reads as two mismatched drawings, not as
    // liveliness. The delay lives in the hop below instead, where being a beat
    // apart is exactly what it looks like.
    var scale = 1 + boost;
    var hop = boost;
    var hopLate = pop(at, now, 70);

    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';

    // Measure the whole banner first and shrink it to fit. The widest it ever
    // gets is mid-bounce, so the bounce is in the measurement — sizing to the
    // resting width lets a three-digit combo push the cat off the screen exactly
    // when the player is doing best.
    ctx.font = '800 ' + Math.round(fs) + 'px -apple-system, Segoe UI, sans-serif';
    var nominal = ctx.measureText(game.combo).width;
    var mh0 = fs * 1.45 * grow;
    var wide = nominal * (1 + 0.55 * 0.30)
             + (mascotWidth(mascots.panda, mh0) + mascotWidth(mascots.cat, mh0)) * MAX_POP
             + fs * 0.68;
    var fit = Math.min(1, (W * 0.94) / wide);
    fs *= fit;

    ctx.font = '800 ' + Math.round(fs * (1 + boost * 0.55)) + 'px -apple-system, Segoe UI, sans-serif';
    var half = ctx.measureText(game.combo).width / 2;

    var mh = fs * 1.45 * grow;
    var gap = fs * 0.34;
    var px = W / 2 - half - gap - mascotWidth(mascots.panda, mh) / 2;
    var cx2 = W / 2 + half + gap + mascotWidth(mascots.cat, mh) / 2;
    // The bounce lifts them as well as swelling them: a hop reads as delight
    // where a pulse on its own reads as a loading spinner.
    var py = cy - hop * mh * 0.55;
    var cyy = cy - hopLate * mh * 0.55;

    drawMascot(mascots.panda, px, py, mh, scale);
    drawMascot(mascots.cat, cx2, cyy, mh, scale);

    if (fx.comboMilestone) {
      var age = now - fx.comboMilestone;
      comboHearts(px, py, age, mh, py - 6);
      comboHearts(cx2, cyy, age, mh, cyy - 6);
    }

    ctx.lineWidth = Math.max(3, fs * 0.14);
    ctx.strokeStyle = 'rgba(255,255,255,0.95)';
    ctx.strokeText(game.combo, W / 2, cy);
    ctx.fillStyle = '#ff2e88';
    ctx.fillText(game.combo, W / 2, cy);

    ctx.font = '700 ' + Math.round(Math.max(9, fs * 0.22)) + 'px -apple-system, Segoe UI, sans-serif';
    ctx.fillStyle = 'rgba(122,46,92,0.55)';
    ctx.fillText('COMBO', W / 2, cy + fs * 0.66);
  }

  // ---------- frame ----------
  function draw(t) {
    var game = RG.game.current;
    if (!game) return;

    var fx = RG.fx;
    var now = performance.now();
    var approach = RG.game.approachTime();

    clear();
    ctx.save();
    // A bomb shoves the whole corridor. Cheap, and it is the one event that has to
    // be felt rather than read.
    if (fx.shake > 0.01) {
      ctx.translate((Math.random() - 0.5) * fx.shake, (Math.random() - 0.5) * fx.shake);
      fx.shake *= 0.86;
    }

    drawCorridor(Math.max(0, t));
    drawStage(now, fx);

    // Tails behind heads, and everything far before everything near: with no depth
    // buffer the draw order is the depth order.
    var notes = game.notes;
    var visible = [];
    for (var i = game.missPointer; i < notes.length; i++) {
      var n = notes[i];
      var dt = n.time - t;
      if (dt > approach) break;
      if (n.judged) continue;
      if (dt < -C.WINDOWS.miss) continue;
      visible.push(n);
    }

    for (var h = 0; h < visible.length; h++) {
      if (visible[h].type === C.HOLD) drawTail(visible[h], t, approach, false);
    }
    for (var a = 0; a < C.COLS; a++) {
      var held = game.activeHolds && game.activeHolds[a];
      if (held) drawTail(held, t, approach, true);
    }

    for (var k = visible.length - 1; k >= 0; k--) {
      var nt = visible[k];
      var dt2 = Math.max(0, nt.time - t);
      var z = depthFor(dt2, approach);
      var p = proj(colX(nt.col), rowY(nt.row), z);
      var r = 0.36 * p.s;
      // Fade in over the first slice of the flight so notes do not pop into
      // existence at the mouth of the corridor.
      var fade = Math.min(1, (1 - dt2 / approach) / 0.10);
      drawNote(nt, p, r, Math.max(0, fade));
    }

    // ---------- effects ----------
    for (var f = fx.hits.length - 1; f >= 0; f--) {
      var burst = fx.hits[f], age = now - burst.at;
      if (age > 300) { fx.hits.splice(f, 1); continue; }
      var pr = age / 300;
      ctx.globalAlpha = 1 - pr;
      ctx.strokeStyle = burst.color;
      ctx.lineWidth = 3;
      ctx.beginPath();
      ctx.arc(burst.x, burst.y, unit * (0.28 + pr * 0.75), 0, Math.PI * 2);
      ctx.stroke();
      ctx.globalAlpha = 1;
    }

    // The streak a finger left behind. Drawn from the game's own record rather
    // than from the live pointer so it outlives the gesture by a few frames.
    for (var s = fx.slashes.length - 1; s >= 0; s--) {
      var sl = fx.slashes[s], sage = now - sl.at;
      if (sage > 190) { fx.slashes.splice(s, 1); continue; }
      ctx.globalAlpha = (1 - sage / 190) * 0.85;
      ctx.strokeStyle = sl.color;
      ctx.lineCap = 'round';
      ctx.lineWidth = 7 * (1 - sage / 190) + 2;
      ctx.beginPath();
      ctx.moveTo(sl.x0, sl.y0);
      ctx.lineTo(sl.x1, sl.y1);
      ctx.stroke();
      ctx.lineCap = 'butt';
      ctx.globalAlpha = 1;
    }

    drawCombo(game, fx, now);

    var us = Math.max(0.72, Math.min(H / 620, 1));

    // Below the hit frame, not above it. Above, it sits squarely in the last
    // half second of every note's flight and covers the thing being judged.
    if (fx.judge) {
      var jAge = now - fx.judge.at;
      if (jAge < 420) {
        ctx.globalAlpha = 1 - jAge / 420;
        ctx.font = '800 ' + Math.round(22 * us) + 'px -apple-system, Segoe UI, sans-serif';
        ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
        ctx.lineWidth = 4;
        ctx.strokeStyle = 'rgba(255,255,255,0.95)';
        var jy = Math.min(H - 16 * us, hitCY + unit * halfH() + 22 * us);
        ctx.strokeText(fx.judge.label, W / 2, jy);
        ctx.fillStyle = fx.judge.color;
        ctx.fillText(fx.judge.label, W / 2, jy);
        ctx.globalAlpha = 1;
      } else fx.judge = null;
    }

    if (t < 0) {
      ctx.font = '800 ' + Math.round(54 * us) + 'px -apple-system, Segoe UI, sans-serif';
      ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
      ctx.lineWidth = 7;
      ctx.strokeStyle = 'rgba(255,255,255,0.95)';
      ctx.strokeText(String(Math.ceil(-t)), W / 2, H * 0.30);
      ctx.fillStyle = '#ff2e88';
      ctx.fillText(String(Math.ceil(-t)), W / 2, H * 0.30);
    }

    ctx.restore();
  }

  // Orientation changes settle a frame or two after the event fires.
  window.addEventListener('resize', resize);
  window.addEventListener('orientationchange', function () { setTimeout(resize, 120); });
  if (window.visualViewport) window.visualViewport.addEventListener('resize', resize);

  RG.render = {
    resize: resize, draw: draw, clear: clear,
    cellCenter: cellCenter, cellUnit: cellUnit,
    // Cells are not square once the rows are spread, so judgement needs both
    // sides — a width-only radius would clip the top and bottom of every target.
    cellSize: function () { return { w: unit, h: unit * rowSpread }; }
  };
})();
