#!/usr/bin/env python3
"""Bake songs/*.mp3 into songs/tracks.js as base64.

Why this exists: browsers block fetch()/XHR on file:// origins, so a page opened
by double-clicking index.html cannot read songs/*.mp3 from disk. Embedding the
audio as base64 in a script file sidesteps that — the bytes arrive as part of the
script itself, no network request involved.

Over http (a local server or GitHub Pages) the game fetches the .mp3 files
directly and never needs this file, so tracks.js is generated locally and left
out of git.

Usage:  python tools/embed-songs.py
"""

import base64
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SONGS = os.path.join(ROOT, "songs")
OUT = os.path.join(SONGS, "tracks.js")


def main():
    if not os.path.isdir(SONGS):
        raise SystemExit("no songs/ directory: %s" % SONGS)

    mp3s = sorted(f for f in os.listdir(SONGS) if f.lower().endswith(".mp3"))
    if not mp3s:
        raise SystemExit("no .mp3 files in %s" % SONGS)

    entries = []
    total = 0
    for name in mp3s:
        path = os.path.join(SONGS, name)
        with open(path, "rb") as f:
            raw = f.read()
        total += len(raw)
        track_id = os.path.splitext(name)[0]
        entries.append((track_id, base64.b64encode(raw).decode("ascii")))
        print("  embedded %-28s %9s bytes" % (name, "{:,}".format(len(raw))))

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* GENERATED by tools/embed-songs.py — do not edit by hand.\n")
        f.write(" * Base64 of songs/*.mp3 so built-in tracks work from file://.\n")
        f.write(" * Regenerate after adding or replacing a song. */\n")
        f.write("RG.embedded = {\n")
        for i, (track_id, b64) in enumerate(entries):
            comma = "," if i < len(entries) - 1 else ""
            f.write("  %s: %s%s\n" % (json.dumps(track_id), json.dumps(b64), comma))
        f.write("};\n")

    out_size = os.path.getsize(OUT)
    print("\n  wrote %s" % os.path.relpath(OUT, ROOT))
    print("  %s mp3 bytes -> %s js bytes" % ("{:,}".format(total), "{:,}".format(out_size)))


if __name__ == "__main__":
    main()
